import type { McpIntegrationConfig } from "@/utils/mcp/types";

export const MCP_INTEGRATIONS: Record<string, McpIntegrationConfig> = {
  notion: {
    name: "notion",
    displayName: "Notion",
    description: "Read and search your Notion workspace via MCP",
    serverUrl: "https://mcp.notion.com/mcp",
    authType: "oauth",
    defaultScopes: ["read"],
    allowedTools: ["notion-search", "notion-fetch"],
    oauthConfig: {
      authUrl: "https://mcp.notion.com/authorize",
      tokenUrl: "https://mcp.notion.com/token",
      registrationUrl: "https://mcp.notion.com/register",
    },
  },
  stripe: {
    name: "stripe",
    displayName: "Stripe",
    description: "Read and search your Stripe data via MCP",
    serverUrl: "https://mcp.stripe.com",
    authType: "oauth", // must request whitelisting of /api/mcp/stripe/callback from Stripe. localhost is whitelisted already.
    // authType: "api-token", // alternatively, use an API token.
    defaultScopes: [],
    allowedTools: [
      // "list_customers",
      // "list_disputes",
      // "list_invoices",
      // "list_payment_intents",
      // "list_prices",
      // "list_products",
      // "list_subscriptions",
      "search_stripe_resources",
    ],
  },
  monday: {
    name: "monday",
    displayName: "Monday.com",
    description: "Create and manage Monday.com boards and items",
    serverUrl: "https://mcp.monday.com",
    authType: "oauth",
    defaultScopes: ["read", "write"],
    allowedTools: [
      "get_board_items_by_name",
      // "create_item",
      // "create_update",
      // "get_board_activity",
      "get_board_info",
      "list_users_and_teams",
      // "create_board",
      // "create_form",
      // "update_form",
      // "get_form",
      // "form_questions_editor",
      // "create_column",
      // "create_group",
      // "all_monday_api",
      // "get_graphql_schema",
      // "get_column_type_info",
      // "get_type_details",
      // "read_docs",
      "workspace_info",
      "list_workspaces",
      // "create_doc",
      // "update_workspace",
      // "update_folder",
      // "create_workspace",
      // "create_folder",
      // "move_object",
      // "create_dashboard",
      // "all_widgets_schema",
      // "create_widget",
    ],
    oauthConfig: {
      authUrl: "https://mcp.monday.com/authorize",
      tokenUrl: "https://mcp.monday.com/token",
    },
  },
  hubspot: {
    name: "hubspot",
    displayName: "HubSpot CRM",
    description: "Access HubSpot CRM data for contacts, deals, and companies",
    serverUrl: "https://mcp.hubspot.com/",
    authType: "oauth",
    defaultScopes: [
      // "crm.objects.contacts.read",
      // "crm.objects.companies.read",
      // "crm.objects.deals.read",
      // "crm.objects.carts.read",
      // "crm.objects.products.read",
      // "crm.objects.orders.read",
      // "crm.objects.line_items.read",
      // "crm.objects.invoices.read",
      // "crm.objects.quotes.read",
      // "crm.objects.subscriptions.read",
      // "crm.objects.users.read",
      // "crm.objects.owners.read",
      "content",
      "crm.objects.companies.read",
      "crm.objects.companies.write",
      "crm.objects.contacts.read",
      "crm.objects.contacts.write",
      "crm.objects.deals.write",
      "forms",
      "oauth",
      "timeline",
    ],
    oauthConfig: {
      authUrl: "https://app.hubspot.com/oauth/authorize",
      tokenUrl: "https://api.hubapi.com/oauth/v1/token",
    },
  },
};

export type IntegrationKey = keyof typeof MCP_INTEGRATIONS;
