import { getModel, type ModelType, type SelectModel } from "@/utils/llms/model";
import type { UserAIFields } from "@/utils/llms/types";

export const LlmUseCase = {
  AssistantChat: "assistant-chat",
  AutomationCheckInMessage: "automation-check-in-message",
  CalendarAvailability: "calendar-availability",
  CategorizeSender: "categorize-sender",
  CategorizeSendersBulk: "categorize-senders-bulk",
  ChatCompaction: "chat-compaction",
  ChatMemoryExtraction: "chat-memory-extraction",
  CleanInbox: "clean-inbox",
  ComposeAutocomplete: "compose-autocomplete",
  ContactInboxPriority: "contact-inbox-priority",
  DetectRecurringPattern: "detect-recurring-pattern",
  DigestEmailSummary: "digest-email-summary",
  DocumentFiling: "document-filing",
  DraftAttachmentSelection: "draft-attachment-selection",
  DraftFollowUp: "draft-follow-up",
  DraftReply: "draft-reply",
  EmailHistoryExtraction: "email-history-extraction",
  EmailReportActionableRecommendations:
    "email-report-actionable-recommendations",
  EmailReportEmailBehavior: "email-report-email-behavior",
  EmailReportExecutiveSummary: "email-report-executive-summary",
  EmailReportLabelAnalysis: "email-report-label-analysis",
  EmailReportResponsePatterns: "email-report-response-patterns",
  EmailReportSummaryGeneration: "email-report-summary-generation",
  EmailReportUserPersona: "email-report-user-persona",
  EnrichContact: "enrich-contact",
  ExtractContacts: "extract-contacts",
  FindSnippets: "find-snippets",
  GenerateFolderInstructions: "generate-folder-instructions",
  KnowledgeExtraction: "knowledge-extraction",
  LearnedWritingStyleCompaction: "learned-writing-style-compaction",
  McpAgent: "mcp-agent",
  MeetingBriefing: "meeting-briefing",
  MeetingWebSearch: "meeting-web-search",
  ParseFilingReply: "parse-filing-reply",
  PersonaAnalysis: "persona-analysis",
  PromptToRules: "prompt-to-rules",
  ProposeRuleFromEmail: "propose-rule-from-email",
  ReplyContextCollector: "reply-context-collector",
  ReplyMemoryExtraction: "reply-memory-extraction",
  ReplyMemorySelection: "reply-memory-selection",
  ReplyNudge: "reply-nudge",
  ResearchCompany: "research-company",
  ScanBusinessCard: "scan-business-card",
  Summarise: "summarise",
  WritingStyleAnalysis: "writing-style-analysis",
} as const;

export type LlmUseCase = (typeof LlmUseCase)[keyof typeof LlmUseCase];

export const LLM_USE_CASE_MODEL_TYPES = {
  [LlmUseCase.AssistantChat]: "chat",
  [LlmUseCase.AutomationCheckInMessage]: "economy",
  [LlmUseCase.CalendarAvailability]: "default",
  [LlmUseCase.CategorizeSender]: "default",
  [LlmUseCase.CategorizeSendersBulk]: "economy",
  [LlmUseCase.ChatCompaction]: "economy",
  [LlmUseCase.ChatMemoryExtraction]: "economy",
  [LlmUseCase.CleanInbox]: "default",
  [LlmUseCase.ComposeAutocomplete]: "default",
  [LlmUseCase.ContactInboxPriority]: "economy",
  [LlmUseCase.DetectRecurringPattern]: "chat",
  [LlmUseCase.DigestEmailSummary]: "economy",
  [LlmUseCase.DocumentFiling]: "economy",
  [LlmUseCase.DraftAttachmentSelection]: "economy",
  [LlmUseCase.DraftFollowUp]: "draft",
  [LlmUseCase.DraftReply]: "draft",
  [LlmUseCase.EmailHistoryExtraction]: "economy",
  [LlmUseCase.EmailReportActionableRecommendations]: "default",
  [LlmUseCase.EmailReportEmailBehavior]: "economy",
  [LlmUseCase.EmailReportExecutiveSummary]: "default",
  [LlmUseCase.EmailReportLabelAnalysis]: "economy",
  [LlmUseCase.EmailReportResponsePatterns]: "default",
  [LlmUseCase.EmailReportSummaryGeneration]: "economy",
  [LlmUseCase.EmailReportUserPersona]: "default",
  [LlmUseCase.EnrichContact]: "chat",
  [LlmUseCase.ExtractContacts]: "economy",
  [LlmUseCase.FindSnippets]: "chat",
  [LlmUseCase.GenerateFolderInstructions]: "chat",
  [LlmUseCase.KnowledgeExtraction]: "economy",
  [LlmUseCase.LearnedWritingStyleCompaction]: "economy",
  [LlmUseCase.McpAgent]: "economy",
  [LlmUseCase.MeetingBriefing]: "default",
  [LlmUseCase.MeetingWebSearch]: "economy",
  [LlmUseCase.ParseFilingReply]: "economy",
  [LlmUseCase.PersonaAnalysis]: "economy",
  [LlmUseCase.PromptToRules]: "chat",
  [LlmUseCase.ProposeRuleFromEmail]: "economy",
  [LlmUseCase.ReplyContextCollector]: "economy",
  [LlmUseCase.ReplyMemoryExtraction]: "economy",
  [LlmUseCase.ReplyMemorySelection]: "economy",
  [LlmUseCase.ReplyNudge]: "chat",
  [LlmUseCase.ResearchCompany]: "chat",
  // Reading a photo needs a vision-capable model, so this rides the chat tier
  [LlmUseCase.ScanBusinessCard]: "chat",
  [LlmUseCase.Summarise]: "default",
  [LlmUseCase.WritingStyleAnalysis]: "default",
} as const satisfies Record<LlmUseCase, ModelType>;

export function getModelForUseCase(
  userAi: UserAIFields,
  useCase: LlmUseCase,
  online = false,
): SelectModel {
  return getModel(userAi, LLM_USE_CASE_MODEL_TYPES[useCase], online);
}
