#!/bin/bash
# Devcontainer setup script - runs after container creation
# Auto-generates all required secrets for local development
set -e

echo "Working directory: $(pwd)"

echo "Installing dependencies..."
pnpm install

echo "Setting up environment..."
cd apps/web
echo "Now in: $(pwd)"

# Only create .env if it doesn't exist (preserve user's OAuth credentials)
if [ ! -f .env ]; then
  echo "Creating .env file with auto-generated secrets..."

  # Generate secrets
  gen_secret() { openssl rand -hex 32; }
  gen_salt() { openssl rand -hex 16; }

  AUTH_SECRET_VAL=$(gen_secret)
  BETTER_AUTH_SECRET_VAL=$(gen_secret)
  EMAIL_ENCRYPT_SECRET_VAL=$(gen_secret)
  EMAIL_ENCRYPT_SALT_VAL=$(gen_salt)
  INTERNAL_API_KEY_VAL=$(gen_secret)
  API_KEY_SALT_VAL=$(gen_salt)
  CRON_SECRET_VAL=$(gen_secret)
  PUBSUB_TOKEN_VAL=$(gen_secret)
  WEBHOOK_STATE_VAL=$(gen_secret)

  cat > .env << EOF
# Auto-generated by devcontainer setup
NEXT_PUBLIC_BASE_URL=http://localhost:3000

# Database (devcontainer services)
DATABASE_URL="postgresql://postgres:password@db:5432/inboxzero?schema=public"
DIRECT_URL="postgresql://postgres:password@db:5432/inboxzero?schema=public"

# Redis (devcontainer services)
UPSTASH_REDIS_URL="http://redis-http:80"
UPSTASH_REDIS_TOKEN="dev_token"
REDIS_URL="redis://redis:6379"

# Auth & encryption (auto-generated)
AUTH_SECRET="${AUTH_SECRET_VAL}"
BETTER_AUTH_SECRET="${BETTER_AUTH_SECRET_VAL}"
EMAIL_ENCRYPT_SECRET="${EMAIL_ENCRYPT_SECRET_VAL}"
EMAIL_ENCRYPT_SALT="${EMAIL_ENCRYPT_SALT_VAL}"
INTERNAL_API_KEY="${INTERNAL_API_KEY_VAL}"
API_KEY_SALT="${API_KEY_SALT_VAL}"
CRON_SECRET="${CRON_SECRET_VAL}"

# Google OAuth - Replace with your keys from https://console.cloud.google.com/apis/credentials
# Redirect URI: http://localhost:3000/api/auth/callback/google
# Using placeholder values to allow app to start - OAuth won't work until replaced
GOOGLE_CLIENT_ID=placeholder-replace-with-real-client-id
GOOGLE_CLIENT_SECRET=placeholder-replace-with-real-client-secret
GOOGLE_PUBSUB_TOPIC_NAME="projects/dev/topics/inbox-zero-dev"
GOOGLE_PUBSUB_VERIFICATION_TOKEN="${PUBSUB_TOKEN_VAL}"

# Microsoft (optional)
MICROSOFT_CLIENT_ID=""
MICROSOFT_CLIENT_SECRET=""
MICROSOFT_WEBHOOK_CLIENT_STATE="${WEBHOOK_STATE_VAL}"

# QStash (leave empty - async jobs disabled)
QSTASH_TOKEN=""
QSTASH_CURRENT_SIGNING_KEY=""
QSTASH_NEXT_SIGNING_KEY=""

# LLM - OpenAI
DEFAULT_LLM_PROVIDER=openai
DEFAULT_LLM_MODEL=gpt-4o
CHAT_LLM_PROVIDER=openai
CHAT_LLM_MODEL=gpt-4o-mini
ECONOMY_LLM_PROVIDER=openai
ECONOMY_LLM_MODEL=gpt-4o-mini
# TODO: Add your OpenAI key from https://platform.openai.com/api-keys
OPENAI_API_KEY=

# Dev settings
NEXT_PUBLIC_BYPASS_PREMIUM_CHECKS=true
EOF
else
  echo ".env already exists, skipping generation (preserving your OAuth credentials)"
fi

echo "Running database migrations..."
npx prisma migrate dev --name init 2>/dev/null || npx prisma db push

echo ""
echo "=========================================="
echo "Setup complete!"
echo ""
echo "Next: Edit apps/web/.env and add your API keys:"
echo "  - GOOGLE_CLIENT_ID"
echo "  - GOOGLE_CLIENT_SECRET"
echo "  - OPENAI_API_KEY"
echo ""
echo "Then run: pnpm dev"
echo "=========================================="
