name: "Build Inbox Zero Docker Images"
run-name: "Build ${{ github.ref_name }} by @${{ github.actor }}"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE_REGISTRY: "ghcr.io"
  DOCKER_USERNAME: ${{ github.actor }}

jobs:

  set-version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.increment_tag.outputs.new_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous Git tag
        id: get_previous_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || cat version.txt)
          echo "Previous tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Increment tag
        id: increment_tag
        run: |
          PREV_TAG="${{ steps.get_previous_tag.outputs.tag }}"
          VERSION="${PREV_TAG#v}"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"
          echo "New tag: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "$NEW_TAG" > version.txt

      - name: Push Git Tag
        id: push_git_tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          NEW_TAG="${{ steps.increment_tag.outputs.new_tag }}"

          echo "Tag pushed to GitHub: $NEW_TAG"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

  build-frontend:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    needs:
      - set-version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_IMAGE_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.web
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.DOCKER_USERNAME }}/inbox-zero:latest
            ghcr.io/${{ env.DOCKER_USERNAME }}/inbox-zero:${{ needs.set-version.outputs.version }}
